### ISSUE TITLE
Can I use this program?

### ISSUE THREAD

**Issue by ghost** [ntim/famous#1]
Hello Sir,
I have tried to compile this program because I need to incorporate the package of G4SiPM to my project, but there is a crash and like this.

`Error in <UnknownClass::InitInterpreter()>: LLVM SYMBOLS ARE EXPOSED TO CLING! This will cause problems; please hide them or dlopen() them after the call to TROOT::InitInterpreter()!

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 4 (Thread 0x7f81c7541700 (LWP 23941)):
#0  0x00007f81de660dfd in poll () at /usr/lib64/libc.so.6
#1  0x00007f81e5d43dc8 in qt_safe_poll(pollfd*, int, int, bool) () at /usr/lib64/libQtCore.so.4
#2  0x00007f81e5cf3c88 in QProcessManager::run() () at /usr/lib64/libQtCore.so.4
#3  0x00007f81e5c1011f in QThreadPrivate::start(void*) () at /usr/lib64/libQtCore.so.4
#4  0x00007f81de93cdc5 in start_thread () at /usr/lib64/libpthread.so.0
#5  0x00007f81de66b73d in clone () at /usr/lib64/libc.so.6

Thread 3 (Thread 0x7f81ba3ad700 (LWP 23943)):
#0  0x00007f81de9406d5 in pthread_cond_wait

GLIBC_2.3.2 () at /usr/lib64/libpthread.so.0
#1  0x00007f81c162b483 in thread_function () at /usr/lib64/dri/swrast_dri.so
#2  0x00007f81c162afa7 in impl_thrd_routine () at /usr/lib64/dri/swrast_dri.so
#3  0x00007f81de93cdc5 in start_thread () at /usr/lib64/libpthread.so.0
#4  0x00007f81de66b73d in clone () at /usr/lib64/libc.so.6

Thread 2 (Thread 0x7f81b9bac700 (LWP 23944)):
#0  0x00007f81de9406d5 in pthread_cond_wait

GLIBC_2.3.2 () at /usr/lib64/libpthread.so.0
#1  0x00007f81c162b483 in thread_function () at /usr/lib64/dri/swrast_dri.so
#2  0x00007f81c162afa7 in impl_thrd_routine () at /usr/lib64/dri/swrast_dri.so
#3  0x00007f81de93cdc5 in start_thread () at /usr/lib64/libpthread.so.0
#4  0x00007f81de66b73d in clone () at /usr/lib64/libc.so.6

Thread 1 (Thread 0x7f81ef612a80 (LWP 23940)):
#0  0x00007f81de6322c9 in waitpid () at /usr/lib64/libc.so.6
#1  0x00007f81de5b5c72 in do_system () at /usr/lib64/libc.so.6
#2  0x00007f81de5b6021 in system () at /usr/lib64/libc.so.6
#3  0x00007f81ee545699 in TUnixSystem::StackTrace() (this=0xc0c6f0) at /root/root-6.08.06/core/unix/src/TUnixSystem.cxx:2405
#4  0x00007f81ee547f6c in TUnixSystem::DispatchSignals(ESignals) (this=0xc0c6f0, sig=kSigSegmentationViolation) at /root/root-6.08.06/core/unix/src/TUnixSystem.cxx:3625
#5  0x00007f81de944370 in <signal handler called> () at /usr/lib64/libpthread.so.0
#6  0x00007f81ba8dff53 in llvm::PMTopLevelManager::addImmutablePass(llvm::ImmutablePass*) () at /usr/lib64/libLLVM-3.8-mesa.so
#7  0x00007f81ba8e1c1b in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) () at /usr/lib64/libLLVM-3.8-mesa.so
#8  0x00007f81b7ed0756 in addPassesToGenerateCode(llvm::LLVMTargetMachine*, llvm::legacy::PassManagerBase&, bool, void const*, void const*, void const*, llvm::MachineFunctionInitializer*) () at /usr/local/root/6.08.06/lib/libCling.so
#9  0x00007f81b7ed0d98 in llvm::LLVMTargetMachine::addPassesToEmitFile(llvm::legacy::PassManagerBase&, llvm::raw_pwrite_stream&, llvm::TargetMachine::CodeGenFileType, bool, void const*, void const*, void const*, llvm::MachineFunctionInitializer*) () at /usr/local/root/6.08.06/lib/libCling.so
#10 0x00007f81bb2e2fb1 in std::_Function_handler<llvm::object::OwningBinary<llvm::object::ObjectFile> (llvm::Module&), llvm::orc::SimpleCompiler>::_M_invoke(std::_Any_data const&, llvm::Module&) () at /usr/lib64/libLLVM-3.8-mesa.so
#11 0x00007f81b70cb1ad in llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer> >::EmissionDeferredSetImpl<std::vector<llvm::Module*, std::allocator<llvm::Module*> >, std::unique_ptr<cling::Azog, std::default_delete<cling::Azog> >, std::unique_ptr<llvm::orc::LambdaResolver<cling::IncrementalJIT::addModules(std::vector<llvm::Module*, std::allocator<llvm::Module*> >&&)::{lambda(std::string const&)#1}, cling::IncrementalJIT::addModules(std::vector<llvm::Module*, std::allocator<llvm::Module*> >&&)::{lambda(std::string const&)#2}>, std::default_delete<{lambda(std::string const&)#2}> > >::emitToBaseLayer(llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer>&) () at /usr/local/root/6.08.06/lib/libCling.so
#12 0x00007f81b70c6fe8 in std::_Function_handler<unsigned long (), llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer> >::EmissionDeferredSet::find(llvm::StringRef, bool, llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer>&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () at /usr/local/root/6.08.06/lib/libCling.so
#13 0x00007f81b70c4f5e in cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction const&) () at /usr/local/root/6.08.06/lib/libCling.so
#14 0x00007f81b7074faf in cling::Interpreter::executeTransaction(cling::Transaction&) () at /usr/local/root/6.08.06/lib/libCling.so
#15 0x00007f81b70ccec4 in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&) () at /usr/local/root/6.08.06/lib/libCling.so
#16 0x00007f81b707891b in cling::Interpreter::Interpreter(int, char const* const*, char const*, bool, cling::Interpreter const*) () at /usr/local/root/6.08.06/lib/libCling.so
#17 0x00007f81b7001138 in TCling::TCling(char const*, char const*) (noRuntime=false, llvmdir=0x1e80168 "/usr/local/root/6.08.06/etc/cling", argv=0x1e80060, argc=8, this=0x1e801b0) at /root/root-6.08.06/interpreter/cling/include/cling/Interpreter/Interpreter.h:303
#18 0x00007f81b7001138 in TCling::TCling(char const*, char const*) (this=0x1e7f9c0, name=<optimized out>, title=<optimized out>) at /root/root-6.08.06/core/meta/src/TCling.cxx:1113
#19 0x00007f81b700234e in CreateInterpreter(void*) (interpLibHandle=<optimized out>) at /root/root-6.08.06/core/meta/src/TCling.cxx:593
#20 0x00007f81ee3d3058 in TROOT::InitInterpreter() (this=0x7f81ee85da00 <ROOT::Internal::GetROOT1()::alloc>) at /root/root-6.08.06/core/base/src/TROOT.cxx:1920
#21 0x00007f81ee3d33d6 in ROOT::Internal::GetROOT2() () at /root/root-6.08.06/core/base/src/TROOT.cxx:364
#22 0x00007f81ee460e46 in TEnv::Getvalue(char const*) (this=0xc0e200, name=0x7f81ee58e976 "Url.Special") at /root/root-6.08.06/core/base/src/TEnv.cxx:459
#23 0x00007f81ee4614d9 in TEnv::GetValue(char const*, char const*) (this=<optimized out>, name=<optimized out>, dflt=0x7f81ee58e9b0 "file: rfio: hpss: castor: dcache: dcap:") at /root/root-6.08.06/core/base/src/TEnv.cxx:542
#24 0x00007f81ee4b1161 in TUrl::GetSpecialProtocols() () at /root/root-6.08.06/core/base/src/TUrl.cxx:594
#25 0x00007f81ee4b17ee in TUrl::SetUrl(char const*, bool) (this=this
entry=0x1e7d130, url=url
entry=0x1d7ef08 "./results/famous_20171123T004154.450469.root", defaultIsFile=defaultIsFile
entry=true) at /root/root-6.08.06/core/base/src/TUrl.cxx:144
#26 0x00007f81ee4b1e1f in TUrl::TUrl(char const*, bool) (this=0x1e7d130, url=0x1d7ef08 "./results/famous_20171123T004154.450469.root", defaultIsFile=<optimized out>) at /root/root-6.08.06/core/base/src/TUrl.cxx:78
#27 0x00007f81eded3550 in TFile::TFile(char const*, char const*, char const*, int) (this=0x1e7cf40, fname1=0x1d7ef08 "./results/famous_20171123T004154.450469.root", option=0x7f81ea53918b "RECREATE", ftitle=0x7f81ea538e6e "", compress=1) at /root/root-6.08.06/io/io/src/TFile.cxx:323
#28 0x00007f81ea5310f7 in RootPersistVisitor::open(std::string) () at /home/local1/Desktop/famous/build/externals/g4sipm/sample/libg4sipm_sample.so
#29 0x00007f81ea52ed2d in PersistencyHandler::open(std::string) () at /home/local1/Desktop/famous/build/externals/g4sipm/sample/libg4sipm_sample.so
#30 0x00007f81eb1c3a77 in CoreRunAction::BeginOfRunAction(G4Run const*) () at /home/local1/Desktop/famous/build/core/libcore.so
#31 0x00007f81eb3f11ce in FamousRunAction::BeginOfRunAction(G4Run const*) () at /home/local1/Desktop/famous/build/sim/libfamous_sim.so
#32 0x00007f81e42bf270 in G4RunManager::RunInitialization() () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#33 0x00007f81e42b8f9d in G4RunManager::BeamOn(int, char const*, int) () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#34 0x00007f81e42d2259 in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#35 0x00007f81e070317f in G4UIcommand::DoIt(G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#36 0x00007f81e0720589 in G4UImanager::ApplyCommand(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#37 0x00007f81e06f003d in G4UIbatch::ExecCommand(G4String const&) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#38 0x00007f81e06f176b in G4UIbatch::SessionStart() () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#39 0x00007f81e0717953 in G4UImanager::ExecuteMacroFile(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#40 0x00007f81e070bcaa in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#41 0x00007f81e070317f in G4UIcommand::DoIt(G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#42 0x00007f81e0720589 in G4UImanager::ApplyCommand(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#43 0x000000000040de22 in main ()
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f81ba8dff53 in llvm::PMTopLevelManager::addImmutablePass(llvm::ImmutablePass*) () at /usr/lib64/libLLVM-3.8-mesa.so
#7  0x00007f81ba8e1c1b in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) () at /usr/lib64/libLLVM-3.8-mesa.so
#8  0x00007f81b7ed0756 in addPassesToGenerateCode(llvm::LLVMTargetMachine*, llvm::legacy::PassManagerBase&, bool, void const*, void const*, void const*, llvm::MachineFunctionInitializer*) () at /usr/local/root/6.08.06/lib/libCling.so
#9  0x00007f81b7ed0d98 in llvm::LLVMTargetMachine::addPassesToEmitFile(llvm::legacy::PassManagerBase&, llvm::raw_pwrite_stream&, llvm::TargetMachine::CodeGenFileType, bool, void const*, void const*, void const*, llvm::MachineFunctionInitializer*) () at /usr/local/root/6.08.06/lib/libCling.so
#10 0x00007f81bb2e2fb1 in std::_Function_handler<llvm::object::OwningBinary<llvm::object::ObjectFile> (llvm::Module&), llvm::orc::SimpleCompiler>::_M_invoke(std::_Any_data const&, llvm::Module&) () at /usr/lib64/libLLVM-3.8-mesa.so
#11 0x00007f81b70cb1ad in llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer> >::EmissionDeferredSetImpl<std::vector<llvm::Module*, std::allocator<llvm::Module*> >, std::unique_ptr<cling::Azog, std::default_delete<cling::Azog> >, std::unique_ptr<llvm::orc::LambdaResolver<cling::IncrementalJIT::addModules(std::vector<llvm::Module*, std::allocator<llvm::Module*> >&&)::{lambda(std::string const&)#1}, cling::IncrementalJIT::addModules(std::vector<llvm::Module*, std::allocator<llvm::Module*> >&&)::{lambda(std::string const&)#2}>, std::default_delete<{lambda(std::string const&)#2}> > >::emitToBaseLayer(llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer>&) () at /usr/local/root/6.08.06/lib/libCling.so
#12 0x00007f81b70c6fe8 in std::_Function_handler<unsigned long (), llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer> >::EmissionDeferredSet::find(llvm::StringRef, bool, llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer>&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () at /usr/local/root/6.08.06/lib/libCling.so
#13 0x00007f81b70c4f5e in cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction const&) () at /usr/local/root/6.08.06/lib/libCling.so
#14 0x00007f81b7074faf in cling::Interpreter::executeTransaction(cling::Transaction&) () at /usr/local/root/6.08.06/lib/libCling.so
#15 0x00007f81b70ccec4 in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&) () at /usr/local/root/6.08.06/lib/libCling.so
#16 0x00007f81b707891b in cling::Interpreter::Interpreter(int, char const* const*, char const*, bool, cling::Interpreter const*) () at /usr/local/root/6.08.06/lib/libCling.so
#17 0x00007f81b7001138 in TCling::TCling(char const*, char const*) (noRuntime=false, llvmdir=0x1e80168 "/usr/local/root/6.08.06/etc/cling", argv=0x1e80060, argc=8, this=0x1e801b0) at /root/root-6.08.06/interpreter/cling/include/cling/Interpreter/Interpreter.h:303
#18 0x00007f81b7001138 in TCling::TCling(char const*, char const*) (this=0x1e7f9c0, name=<optimized out>, title=<optimized out>) at /root/root-6.08.06/core/meta/src/TCling.cxx:1113
#19 0x00007f81b700234e in CreateInterpreter(void*) (interpLibHandle=<optimized out>) at /root/root-6.08.06/core/meta/src/TCling.cxx:593
#20 0x00007f81ee3d3058 in TROOT::InitInterpreter() (this=0x7f81ee85da00 <ROOT::Internal::GetROOT1()::alloc>) at /root/root-6.08.06/core/base/src/TROOT.cxx:1920
#21 0x00007f81ee3d33d6 in ROOT::Internal::GetROOT2() () at /root/root-6.08.06/core/base/src/TROOT.cxx:364
#22 0x00007f81ee460e46 in TEnv::Getvalue(char const*) (this=0xc0e200, name=0x7f81ee58e976 "Url.Special") at /root/root-6.08.06/core/base/src/TEnv.cxx:459
#23 0x00007f81ee4614d9 in TEnv::GetValue(char const*, char const*) (this=<optimized out>, name=<optimized out>, dflt=0x7f81ee58e9b0 "file: rfio: hpss: castor: dcache: dcap:") at /root/root-6.08.06/core/base/src/TEnv.cxx:542
#24 0x00007f81ee4b1161 in TUrl::GetSpecialProtocols() () at /root/root-6.08.06/core/base/src/TUrl.cxx:594
#25 0x00007f81ee4b17ee in TUrl::SetUrl(char const*, bool) (this=this
entry=0x1e7d130, url=url
entry=0x1d7ef08 "./results/famous_20171123T004154.450469.root", defaultIsFile=defaultIsFile
entry=true) at /root/root-6.08.06/core/base/src/TUrl.cxx:144
#26 0x00007f81ee4b1e1f in TUrl::TUrl(char const*, bool) (this=0x1e7d130, url=0x1d7ef08 "./results/famous_20171123T004154.450469.root", defaultIsFile=<optimized out>) at /root/root-6.08.06/core/base/src/TUrl.cxx:78
#27 0x00007f81eded3550 in TFile::TFile(char const*, char const*, char const*, int) (this=0x1e7cf40, fname1=0x1d7ef08 "./results/famous_20171123T004154.450469.root", option=0x7f81ea53918b "RECREATE", ftitle=0x7f81ea538e6e "", compress=1) at /root/root-6.08.06/io/io/src/TFile.cxx:323
#28 0x00007f81ea5310f7 in RootPersistVisitor::open(std::string) () at /home/local1/Desktop/famous/build/externals/g4sipm/sample/libg4sipm_sample.so
#29 0x00007f81ea52ed2d in PersistencyHandler::open(std::string) () at /home/local1/Desktop/famous/build/externals/g4sipm/sample/libg4sipm_sample.so
#30 0x00007f81eb1c3a77 in CoreRunAction::BeginOfRunAction(G4Run const*) () at /home/local1/Desktop/famous/build/core/libcore.so
#31 0x00007f81eb3f11ce in FamousRunAction::BeginOfRunAction(G4Run const*) () at /home/local1/Desktop/famous/build/sim/libfamous_sim.so
#32 0x00007f81e42bf270 in G4RunManager::RunInitialization() () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#33 0x00007f81e42b8f9d in G4RunManager::BeamOn(int, char const*, int) () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#34 0x00007f81e42d2259 in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4run.so
#35 0x00007f81e070317f in G4UIcommand::DoIt(G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#36 0x00007f81e0720589 in G4UImanager::ApplyCommand(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#37 0x00007f81e06f003d in G4UIbatch::ExecCommand(G4String const&) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#38 0x00007f81e06f176b in G4UIbatch::SessionStart() () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#39 0x00007f81e0717953 in G4UImanager::ExecuteMacroFile(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#40 0x00007f81e070bcaa in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#41 0x00007f81e070317f in G4UIcommand::DoIt(G4String) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#42 0x00007f81e0720589 in G4UImanager::ApplyCommand(char const*) () at /usr/local/geant4.10.03.p01/lib64/libG4intercoms.so
#43 0x000000000040de22 in main ()`

I have compiled this with Root 6.08.06 and geant4.10.03.p01 I have used ''gdb'' as well,

Thanks,
best regards
Ivancovish J. Huancco

**Comment by ntim** [comment]
Please try again see #2
